---
apiVersion: v1
kind: Secret
metadata:
  name: azuredevops
type: Opaque
data:
  ADV_TOKEN: bas64==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azuredevops
data:
  ADV_POOL: "1"
  ADV_ORG: inc
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: azuredevops
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: azuredevops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azuredevops
  namespace: default
  labels:
    app: azuredevops
spec:
  selector:
    matchLabels:
      app: azuredevops
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: azuredevops
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: azuredevops
        image: imjoseangel/azdvpool
        imagePullPolicy: IfNotPresent
        env:
          - name: ADV_TOKEN
            valueFrom:
              secretKeyRef:
                name: azuredevops
                key: ADV_TOKEN
          - name: ADV_ORG
            valueFrom:
              configMapKeyRef:
                name: azuredevops
                key: ADV_ORG
          - name: ADV_POOL
            valueFrom:
              configMapKeyRef:
                name: azuredevops
                key: ADV_POOL
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
