---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
  namespace: default
  labels:
    app: dummy
spec:
  selector:
    matchLabels:
      app: dummy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dummy
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: dummy
          image: imjoseangel/dummy
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_ADDRESS
              value: "redis.default:6379"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
