---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: dummy
  namespace: default
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: dummy
          image: imjoseangel/dummy
          imagePullPolicy: Always
          command: ["echo",  "dummy"]
        restartPolicy: Never
    parallelism: 1
    completions: 1
    backoffLimit: 4
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "1"
        url: "http://azuredevops.default.svc.cluster.local:8080"
        valueLocation: "runningjobs"
