---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: scaleset
  namespace: default
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: scaleset
          image: imjoseangel/scaleset
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config-volume
            mountPath: /usr/local/sbin/config.ini
            subPath: config.ini
          env:
            - name: ARM_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azscalesetsp
                  key: ARM_CLIENT_ID
            - name: ARM_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azscalesetsp
                  key: ARM_CLIENT_SECRET
            - name: ARM_SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  name: azscalesetsp
                  key: ARM_SUBSCRIPTION_ID
            - name: ARM_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azscalesetsp
                  key: ARM_TENANT_ID
        volumes:
          - name: config-volume
            configMap:
              name: scaleset-ini-config
        restartPolicy: Never
    parallelism: 1
    completions: 1
    backoffLimit: 1
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "1"
        url: "http://azuredevops.default.svc.cluster.local:8080"
        valueLocation: "runningjobs"
